# Rate Limiting Zones
limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=loginlimit:10m rate=5r/m;
limit_req_status 429;

# Redireciona HTTP para HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name _;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Servidor principal (HTTPS)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # Otimizações básicas de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Limite específico para rota de login (evitar brute-force)
    location /api/auth/callback/credentials {
        limit_req zone=loginlimit burst=5 nodelay;
        proxy_pass http://app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        limit_req zone=mylimit burst=20 nodelay;
        # O host "app" refere-se ao serviço app no docker-compose
        proxy_pass http://app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_cache_bypass $http_upgrade;
    }
}
